services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=task_user
      - POSTGRES_PASSWORD=task_password
      - POSTGRES_DB=task_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_api"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: